import unittest
from doubly_linked_list import Node, DoublyLinkedList

class TestNode(unittest.TestCase):
    def test_initialization(self):
        node = Node(5)
        self.assertEqual(node.val, 5)
        self.assertIsNone(node.next)
        self.assertIsNone(node.prev)
        
    def test_modify_val(self):
        node = Node(10)
        node.val = 20
        self.assertEqual(node.val, 20)
        
    def test_modify_next(self):
        node1 = Node(1)
        node2 = Node(2)
        node1.next = node2
        self.assertIs(node1.next, node2)
        
    def test_modify_prev(self):
        node1 = Node(1)
        node2 = Node(2)
        node1.prev = node2
        self.assertIs(node1.prev, node2)

    def test_initialization_with_next_prev(self):
        node1 = Node(1)
        node2 = Node(2, node1, node1)
        self.assertEqual(node2.val, 2)
        self.assertIs(node2.next, node1)
        self.assertIs(node2.prev, node1)

# Your MyLinkedList object will be instantiated and called as such:
# obj = MyLinkedList()
# param_1 = obj.get(index)
# obj.addAtHead(val)
# obj.addAtTail(val)
# obj.addAtIndex(index,val)
# obj.deleteAtIndex(index

class TestDoublyLinkedList(unittest.TestCase):
    def test_initialization(self):
        dll = DoublyLinkedList()
        self.assertIsNone(dll.head)
        self.assertIsNone(dll.tail)
        self.assertEqual(dll.size, 0)

    def test_add_at_head(self):
        dll = DoublyLinkedList()
        dll.addAtHead(1)
        self.assertEqual(dll.head.val, 1)
        self.assertEqual(dll.tail.val, 1)
        self.assertEqual(dll.size, 1)
        self.assertIsNone(dll.head.next)
        self.assertIsNone(dll.head.prev)
        self.assertIsNone(dll.tail.next)
        self.assertIsNone(dll.tail.prev)
        dll.addAtHead(2)
        self.assertEqual(dll.head.val, 2)
        self.assertEqual(dll.tail.val, 1)
        self.assertEqual(dll.size, 2)
        self.assertIsNone(dll.head.prev)
        self.assertIsNone(dll.tail.next)
        self.assertIs(dll.head.next, dll.tail)
        self.assertIs(dll.tail.prev, dll.head)

    def test_add_at_tail(self):
        dll = DoublyLinkedList()
        dll.addAtTail(1)
        self.assertEqual(dll.head.val, 1)
        self.assertEqual(dll.tail.val, 1)
        self.assertEqual(dll.size, 1)
        self.assertIsNone(dll.head.next)
        self.assertIsNone(dll.head.prev)
        self.assertIsNone(dll.tail.next)
        self.assertIsNone(dll.tail.prev)
        dll.addAtTail(2)
        self.assertEqual(dll.head.val, 1)
        self.assertEqual(dll.tail.val, 2)
        self.assertEqual(dll.size, 2)
        self.assertIsNone(dll.head.prev)
        self.assertIsNone(dll.tail.next)
        self.assertIs(dll.head.next, dll.tail)
        self.assertIs(dll.tail.prev, dll.head)
        
    def test_add_at_index(self):
        dll = DoublyLinkedList()
        dll.addAtIndex(0, 1)
        self.assertEqual(dll.head.val, 1)
        self.assertEqual(dll.tail.val, 1)
        self.assertEqual(dll.size, 1)
        self.assertIsNone(dll.head.next)
        self.assertIsNone(dll.head.prev)
        self.assertIsNone(dll.tail.next)
        self.assertIsNone(dll.tail.prev)
        dll.addAtIndex(0, 2)
        self.assertEqual(dll.head.val, 2)
        self.assertEqual(dll.tail.val, 1)
        self.assertEqual(dll.size, 2)
        self.assertIsNone(dll.head.prev)
        self.assertIsNone(dll.tail.next)
        self.assertIs(dll.head.next, dll.tail)
        self.assertIs(dll.tail.prev, dll.head)
        dll.addAtIndex(1, 3)
        self.assertEqual(dll.head.val, 2)
        self.assertEqual(dll.tail.val, 1)
        self.assertEqual(dll.size, 3)
        self.assertIsNone(dll.head.prev)
        self.assertIsNone(dll.tail.next)
        dll.addAtIndex(3, 4)
        self.assertEqual(dll.head.val, 2)
        self.assertEqual(dll.tail.val, 4)
        self.assertEqual(dll.size, 4)
        self.assertIsNone(dll.head.prev)
        self.assertIsNone(dll.tail.next)
        self.assertIs(dll.head.next.next.next, dll.tail)
        self.assertIs(dll.tail.prev.prev.prev, dll.head)
        dll.addAtIndex(2, 5)
        self.assertEqual(dll.head.val, 2)
        self.assertEqual(dll.tail.val, 4)
        self.assertEqual(dll.size, 5)
        self.assertIsNone(dll.head.prev)
        self.assertIsNone(dll.tail.next)

    def test_delete_at_index(self):
        # delete from empty list
        dll = DoublyLinkedList()
        dll.deleteAtIndex(0)
        self.assertEqual(dll.size, 0)
        self.assertIsNone(dll.head)
        self.assertIsNone(dll.tail)
        # delete from list with one node
        dll.addAtHead(1)
        dll.deleteAtIndex(0)
        self.assertEqual(dll.size, 0)
        self.assertIsNone(dll.head)
        self.assertIsNone(dll.tail)
        # delete from list with two nodes
        dll.addAtHead(1)
        dll.addAtHead(2)
        dll.deleteAtIndex(1)
        self.assertEqual(dll.size, 1)
        self.assertIs(dll.head, dll.tail)
        self.assertIsNone(dll.head.prev)
        self.assertIsNone(dll.head.next)
        # delete from list with three nodes
        dll.addAtHead(3)
        self.assertEqual(dll.size, 2)
        dll.addAtHead(2)
        self.assertEqual(dll.size, 3)
        dll.addAtHead(1)
        self.assertEqual(dll.size, 4)
        dll.deleteAtIndex(1)
        self.assertEqual(dll.size, 3)
        self.assertIsNone(dll.head.prev)
        self.assertIsNone(dll.tail.next)
        self.assertIs(dll.head.next.next, dll.tail)
        self.assertIs(dll.tail.prev.prev, dll.head)
        dll.deleteAtIndex(1)
        self.assertEqual(dll.size, 2)
        self.assertIsNone(dll.head.prev)
        self.assertIsNone(dll.tail.next)
        self.assertIs(dll.head.next, dll.tail)
        self.assertIs(dll.tail.prev, dll.head)
        dll.deleteAtIndex(0)
        self.assertEqual(dll.size, 1)
        self.assertIsNone(dll.head.prev)
        self.assertIsNone(dll.tail.next)
        self.assertIs(dll.head, dll.tail)
        dll.deleteAtIndex(0)
        self.assertEqual(dll.size, 0)
        self.assertIsNone(dll.head)
        self.assertIsNone(dll.tail)
            
    def test_get_index(self):
        dll = DoublyLinkedList()
        self.assertIsNone(dll.get(0))
        dll.addAtHead(1)
        self.assertEqual(dll.get(0), 1)
        dll.addAtHead(2)
        self.assertEqual(dll.get(0), 2)
        self.assertEqual(dll.get(1), 1)
        dll.addAtTail(3)
        self.assertEqual(dll.get(2), 3)
        self.assertIsNone(dll.get(3))
        dll.addAtIndex(1, 4)
        self.assertEqual(dll.get(1), 4)
        self.assertEqual(dll.get(2), 1)
        self.assertEqual(dll.get(3), 3)
        self.assertIsNone(dll.get(4))
        dll.deleteAtIndex(1)
        self.assertEqual(dll.get(1), 1)
        self.assertEqual(dll.get(2), 3)
        self.assertIsNone(dll.get(3))
        dll.deleteAtIndex(1)
        self.assertEqual(dll.get(1), 3)
        self.assertIsNone(dll.get(2))
        dll.deleteAtIndex(0)
        self.assertEqual(dll.get(0), 3)
        self.assertIsNone(dll.get(1))
        dll.deleteAtIndex(0)
        self.assertIsNone(dll.get(0))

if __name__ == '__main__':
    unittest.main()
